### ISSUE TITLE
OutOfRangeError

### ISSUE THREAD

**Issue by huaibovip** [cchen-cc/Robust-Mseg#2]
**My environment：**
- python： 3.6.2
- cuda: 9.0
- cudnn: 7.5.6

When run the code, I got this error, as follow：

> In the epoch  0
> Traceback (most recent call last):
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
>     return fn(*args)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)
> 	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/public/home/hb/projects/Robust-Mseg-main/main.py", line 439, in <module>
>     main()
>   File "/public/home/hb/projects/Robust-Mseg-main/main.py", line 435, in main
>     multimodal_model.train()
>   File "/public/home/hb/projects/Robust-Mseg-main/main.py", line 311, in train
>     data_feed, label_feed = sess.run([data, label])
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
>     run_metadata_ptr)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
>     run_metadata)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)
> 	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
> 
> Caused by op 'shuffle_batch', defined at:
>   File "/public/home/hb/projects/Robust-Mseg-main/main.py", line 439, in <module>
>     main()
>   File "/public/home/hb/projects/Robust-Mseg-main/main.py", line 435, in main
>     multimodal_model.train()
>   File "/public/home/hb/projects/Robust-Mseg-main/main.py", line 266, in train
>     gt_flag=True, crop_size=CROP_SIZE, num_cls=NUM_CLS)
>   File "/public/home/hb/projects/Robust-Mseg-main/data_loader.py", line 66, in load_data
>     50, 10, num_threads=1) 
https://github.com/cchen-cc/Robust-Mseg/blob/094cfd654a54227ac8c9e37daf3feb0f10a4e46f/data_loader.py#L64
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch
>     name=name)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 846, in _shuffle_batch
>     dequeued = queue.dequeue_many(batch_size, name=name)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
>     self._queue_ref, n=n, component_types=self._dtypes, name=name)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
>     component_types=component_types, timeout_ms=timeout_ms, name=name)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
>     op_def=op_def)
>   File "/public/home/hb/.miniconda3/envs/py36_tf110/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> OutOfRangeError (see above for traceback): RandomShuffleQueue '_3_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 1, current size 0)
> 	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
> 
> 
> 进程已结束，退出代码为 1

Could you help me solve this problem？
Thanks！

**Comment by gardenlee21** [comment]
@huaibovip Did you fix it? Please share how to solve it ...
